# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://kunzaatko.github.io"

title = "Random Sampler"
author = "Martin Kunz"
description = "Personal blog of Martin Kunz" # TODO: Update... Appears in feeds <16-03-24> 

default_language = "en"

output_dir = "public"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
  { name = "tags", feed = true },
  { name = "categories", feed = true },
]
taxonomy_root = "blog"

build_search_index = true
generate_sitemap = true
generate_robots_txt = true

[markdown]
render_emoji = true
smart_punctuation = true
definition_list = true
github_alerts = true

# CSS class to add to external links (e.g. "external-link")
# external_links_class = 

# TODO: Allow for light and dark themes similarly as it is in rust <19-01-26> 
[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"
error_on_missing_language = true
extra_grammars = ["highlight/syntaxes/julia-repl.json"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_path = false
include_content = true

[extra]
date_format = "%b. %d, %Y"
primary_color = "#da532c"
source_url = "https://github.com/kunzaatko/kunzaatko.github.io"

[extra.nav]
links = [
  { url = "$BASE_URL/blog", name = "Blog", icon = '<i class="fa-solid fa-blog"></i>' },
  { url = "$BASE_URL/about", name = "About", icon = '<i class="fa-solid fa-address-card"></i>' },
  # { url = "$BASE_URL/tags", name = "Tags", icon = '<i class="fa-solid fa-tags"></i>' },
  # { url = "$BASE_URL/categories", name = "Categories", icon = '<i class="fa-solid fa-cubes"></i>' },
]

[extra.author]
name = "Martin Kunz"
# avatar =
